[package]

name = "heliotrope"
version = "0.0.1"
authors = ["Valentin Vasilyev <valentin.vasilyev@outlook.com>"]

[dependencies.http]
git = "https://github.com/chris-morgan/rust-http"

[dependencies.url]
git = "https://github.com/servo/rust-url"

